# Generated by Django 4.2.6 on 2023-11-16 03:16

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('IdCliente', models.CharField(max_length=13, primary_key=True, serialize=False)),
                ('Nombres', models.CharField(max_length=30)),
                ('ApPaterno', models.CharField(max_length=15)),
                ('ApMaterno', models.CharField(max_length=15)),
                ('FechaNacimiento', models.DateField()),
                ('Correo', models.EmailField(max_length=50, unique=True)),
                ('Telefono', models.CharField(max_length=12, unique=True)),
                ('Direccion', models.CharField(max_length=100)),
                ('CondPago', models.CharField(choices=[('C', 'Contado'), ('X', 'Crédito'), ('E', 'Efectivo')], default='C', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Productos',
            fields=[
                ('IdProducto', models.CharField(help_text='Ingrese el Nro. de Modelo', max_length=10, primary_key=True, serialize=False)),
                ('ImagenProducto', models.ImageField(upload_to='ImgProducto/')),
                ('PrecioUnitario', models.DecimalField(decimal_places=2, default=0, help_text='Ingrese precio unitario neto', max_digits=8)),
                ('Descripcion', ckeditor.fields.RichTextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ventas',
            fields=[
                ('IdVenta', models.AutoField(primary_key=True, serialize=False)),
                ('FechaVenta', models.DateField()),
                ('CondPago', models.CharField(max_length=1)),
                ('TotalVenta', models.DecimalField(decimal_places=0, default=0, max_digits=10)),
                ('IdCliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ArteNativo.clientes')),
            ],
        ),
        migrations.CreateModel(
            name='DetalleVenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Cantidad', models.IntegerField(default=1, max_length=4)),
                ('PrecioLinea', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('TotalLinea', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('IdProducto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ArteNativo.productos')),
                ('IdVenta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ArteNativo.ventas')),
            ],
        ),
    ]
