# Generated by Django 4.2.6 on 2023-11-16 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ArteNativo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalleventa',
            name='Cantidad',
            field=models.IntegerField(default=1),
        ),
    ]
