# Generated by Django 4.2.6 on 2023-11-16 03:48

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ArteNativo', '0002_alter_detalleventa_cantidad'),
    ]

    operations = [
        migrations.AddField(
            model_name='productos',
            name='NombreProducto',
            field=models.CharField(default='Descripción corta', help_text='Ingrese una descripción breve del producto', max_length=50),
        ),
        migrations.AlterField(
            model_name='productos',
            name='Descripcion',
            field=ckeditor.fields.RichTextField(blank=True, help_text='Haga una presentación del producto.', null=True),
        ),
    ]
