# Generated by Django 4.2.7 on 2023-11-16 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ArteNativo', '0003_productos_nombreproducto_alter_productos_descripcion'),
    ]

    operations = [
        migrations.AddField(
            model_name='productos',
            name='Stock',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='productos',
            name='TipoProducto',
            field=models.CharField(choices=[('A', 'Domirtorio'), ('B', 'Sala'), ('C', 'Comedor'), ('D', 'Cocina'), ('E', 'Exteriores'), ('F', 'Decoración')], default='B', max_length=1),
        ),
    ]
