# Generated by Django 4.2.6 on 2023-11-20 17:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ArteNativo', '0004_productos_stock_productos_tipoproducto'),
    ]

    operations = [
        migrations.AddField(
            model_name='productos',
            name='EstadoProducto',
            field=models.BooleanField(choices=[(True, 'Activo'), (False, 'Inactivo')], default=True),
        ),
        migrations.CreateModel(
            name='CArritoItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Cantidad', models.PositiveIntegerField(default=1)),
                ('CodProducto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ArteNativo.productos')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
